### ISSUE TITLE
Library for Arduino / ESP32

### ISSUE THREAD

**Issue by medisoft** [guaix-ucm/tesstractor#11]
Hello! I'm wondering if it could be done, to create a ESP32 connector, that from one side, uses the Serial1 to USB to connect to a SQM, and on the other side, uses Wifi/Bluetooth to stream the data to a mqttt server o similar.

In theory it may be done, as those devices have enough power and ram, but I'm wondering if you have plans to create a version for those, or if you know a way to do the task.

Thanks!

**Comment by sergiopasra** [comment]
Sorry, I'm not familiar with ESP32, so I don't know how to answer your question.
